builds:
  - goos:
      - linux
      - darwin
    goarch:
      - amd64
      - arm64
    binary: webtop
    ignore:
      - goos: darwin
        goarch: amd64
      - goos: linux
        goarch: arm64

      - goos: windows
        goarch: arm64
      - goos: windows
        goarch: arm
      - goos: darwin
        goarch: arm
      - goos: darwin
        goarch: amd64
      - goos: android
        goarch: "386"
      - goos: android
        goarch: amd64
      - goos: android
        goarch: arm
      - goos: darwin
        goarch: "386"
      - goos: freebsd
        goarch: "arm"
      - goos: freebsd
        goarch: "arm64"
    main: goreleaser.go
    hooks:
      #pre:
      #  - /bin/sh -c "if [ ! -e ./goreleaser.go ]; then echo -e 'package main\\\nfunc main() { }' > ./goreleaser.go ; fi"
      post:
        - ./.goreleaser_hook.sh "{{ .Arch }}" "{{ .Os }}" "{{ .Arm }}" "webtop"
checksum:
  name_template: "checksums.txt"
changelog:
  use: github
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
release:
  replace_existing_artifacts: true
  prerelease: auto
